### ISSUE TITLE
Possible to have a new release?

### ISSUE THREAD

**Issue by Sathors** [carrierwaveuploader/carrierwave-i18n#9]
Hi,

the messages now have changed since the version 0.1.0, so it is not working anymore.

Would it be possible to have a new release?

**Comment by mshibuya** [comment]
@bensie @thomasfedb @mehlah How about this?
Could you cut a new release, or add me as another gem owner?

**Comment by thomasfedb** [comment]
@mshibuya you're now a gem owner. Congrats!

**Comment by mshibuya** [comment]
Thanks @thomasfedb , just pushed 0.2.0 release.
https://rubygems.org/gems/carrierwave-i18n/versions/0.2.0

**Comment by Sathors** [comment]
Thanks guys.
